version: '3.3'
services:
  ui:
    image: apache/skywalking-ui:7.0.0
    container_name: ui
    restart: always
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: 10.16.34.48:12800,10.16.32.226:12800,10.16.33.191:12800